# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19082bacb9ef401cead9f48e464c4b2b757f4ce9e8de232ae5652a3bd6bd590470a2d95e29e9149d6db8a9e8afdb2b9b46d8f81b6c8771a204c395a8b5ed5741

test:
  secret_key_base: 04c0b07ce239bfd7449620b921ccf3171f7fd876a22927656275d8cd4ee52d4f0f7124a3f305f0d29a5ab30b8bc039ecd65fd5aae9b86afef9bd3851ad8e0405

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
